plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    
}

android {
    namespace 'com.mehf.smsgateway'
    compileSdk 34
   defaultConfig {
        applicationId "com.mehf.smsgateway.v2" 
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "2.0"
}

dependencies {
    // Purani basic libraries
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'

    // Firebase - Chat & Database 
    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-messaging'

    // OneSignal Notification
    implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'

    implementation 'org.webrtc:google-webrtc:1.0.32006'
}
