plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.mehf.smsgateway'
    compileSdk 34

    defaultConfig {
        applicationId "com.mehf.smsgateway.v2"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // Java version ko 17 par update kiya gaya hai
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

// Ye block purani WebRTC request ko nayi library par force redirect karega
configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.webrtc' && details.requested.name == 'google-webrtc') {
            details.useTarget 'io.getstream:stream-webrtc-android:1.1.1'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-messaging'

    // OneSignal
    implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'

    // WebRTC
    implementation 'io.getstream:stream-webrtc-android:1.1.1'
}
